### ISSUE TITLE
Rails 4.2, Ruby 2.2

### ISSUE THREAD

**Issue by decklin** [railsbridge-boston/railsbridge-vm#10]
If we're going to be using the upstream curriculum, looks like it's expecting Rails 4.1: http://docs.railsbridge.org/installfest/create_a_rails_app

Comment here with any problems using 4.1. (I guess this is not a huge deal for September if we're focusing on Ruby?)

**Comment by decklin** [comment]
Rails 4.2 is now current. I am hoping that we can merge Rails-version-related changes from upstream before 2015-05, so this is open as a reminder to update VM.

**Comment by mxie** [comment]
Yeah, we should just move forward with the upgrade.

**Comment by Silvery-Corgan** [comment]
Hello team,

I am trying to setup a rails bridge VM to start learning rails.

I have done the following:

Downloaded the railsbridgevm-2015-06.box image and starting it up. This works fine but the port forwarding won't work as I start WEBrick.

RailsBridge-VM:~/workspace/$ rails new myapp
RailsBridge-VM:~/workspace/myapp$ cd myapp
RailsBridge-VM:~/workspace/myapp$ rails s
=> Booting WEBrick
=> Rails 4.2.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2015-06-25 20:33:26] INFO  WEBrick 1.3.1
[2015-06-25 20:33:26] INFO  ruby 2.2.2 (2015-04-13) [i686-linux]
[2015-06-25 20:33:26] INFO  WEBrick::HTTPServer#start: pid=1443 port=3000


Now when I'm trying to access http://localhost:3000 or http://127.0.0.1:3000 it would give me a connection has been reset.

When trying to access localhost:2222 I get this:
SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2

Which means that the port forwarding for ssh has been made but not for WEBrick or something is broken.

Not knowing what to do to fix this I started to make my own image. So I proceed with vagrant destroy, erase everything and git clone https://github.com/railsbridge-boston/railsbridge-vm.git

Now before I go into the new folder and start vagrant up I need to fix all those spaces in the .sh files as the provisioning will fail otherwise.

In the provision-root-install.sh file

I delete the space from line 2:
Before:
. /tmp/railsbridge-versions.sh
After:
./tmp/railsbridge-versions.sh

Then I remove lines 27 and 28 and replace them with:
git clone https://github.com/postmodern/chruby.git
cd chruby && make && ./scripts/setup.sh

Same thing for lines 30 and 31 which get replaced by the below:
git clone https://github.com/postmodern/ruby-install.git
cd ruby-install && make && make install

Now that I'm done with this file I go to provision-user-install and remove the spaces on lines 2 and 5
Before:
. /tmp/railsbridge-versions.sh
. /usr/local/share/chruby/chruby.sh
After:
./tmp/railsbridge-versions.sh
./usr/local/share/chruby/chruby.sh

Now I want to change the vagrant file and make it a 64 bit machine. So I change it to trusty64 and the link with the .box file that has 64 bits:
  config.vm.box = "trusty64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

The last thing I want to do is to modify the versions.sh file and replace the install revision with the newest commit SHA which is: "83f2ce5bf1466d52e8faa591630c8cd9a62d6ad1".

Ok, now I go start the deployment with vagrant up and it starts to download all the necessary things and makes the image, however, I am not getting automatic redirection and the moment I do a vagrant ssh I get this error message:

Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-55-generic x86_64)

 * Documentation:  https://help.ubuntu.com/


Last login: Thu Jun 25 21:47:06 2015 from 10.0.2.2
: No such file or directoryc
: No such file or directoryuby/chruby.sh
vagrant@vagrant-ubuntu-trusty-64:~$ cd workspace
vagrant@vagrant-ubuntu-trusty-64:~/workspace$ ls
binfiles  provision-root-cleanup.sh  Rakefile     Vagrantfile.dist
dotfiles  provision-root-install.sh  README.md    versions.sh
etcfiles  provision-user-install.sh  Vagrantfile
vagrant@vagrant-ubuntu-trusty-64:~/workspace$ rails new myapp
The program 'rails' can be found in the following packages:
 * ruby-railties-3.2
 * ruby-railties-4.0
Ask your administrator to install one of them
vagrant@vagrant-ubuntu-trusty-64:~/workspace$

My setup is Windows 7 Enterprise on 64 bits. My virtualbox is at v4.3.28 and vagrant has been installed with the latest stable version.

I got stuck here. Should I install Ubuntu manually and ditch this piece of shit called vagrant or is there a different way of doing things? Can anyone help me with this issue?

**Comment by decklin** [comment]
Hi,

It looks like there is a documentation bug here in that Rails 4.2 requires the option `-b 0.0.0.0` to bind to all interfaces (by default, and this is new in 4.2, it will only listen on 127.0.0.1, which cannot take Vagrant-forwarded connections). :rotating_light: :rotating_light: :rotating_light:  @mxie @gabebw @eudaimonious  can we make sure everyone knows about this tonight? I'm sorry I didn't catch this.

FYI, @Silvery-Corgan, the spaces in the provisioning script are not typos; that is the syntax for sourcing a script in the current shell instead of running it as a child process. This is required to set the version variables in the provisioning script shell process (otherwise they would only be set in the child process and immediately dissapear), and for chruby to work. Also, we're trying to make this project a welcoming environment for interested students and TAs to start contributing to, so could you tone down the language please? Thank you.

**Comment by gabebw** [comment]
@decklin Yes,I'm on it. That means students should run `rails s -b 0.0.0.0`, not just `rails s`, right? I can change it right now.

**Comment by Silvery-Corgan** [comment]
@decklin Sorry if I offended anyone, but it was not what I wanted.Thanks for clearing that out for me. I'll be trying it again.

However, the script fails to install chruby and ruby-install if you try to download the tar.gz files. I would suggest you guys use git clone to do the job. Also, the variables in versions.sh have no dollar sign ($) before their name. I think you need to add them if you want to source that file with a dot sign.

Just my 2 cents. I might be wrong but I'd like to help with this.

**Comment by decklin** [comment]
@gabebw Yes, that command is right.

**Comment by decklin** [comment]
@Silvery-Corgan could you open a new issue with the log you get from `vagrant up` (starting from scratch) when you're encountering a failure? You can gist the complete log and link to it. Thanks.
